config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'

  get 'berita' => 'home#my_news', :as => :public_news
  get 'glosarium' => 'home#glossary', :as => :public_glossary
  get 'tips_investasi' => 'home#investment_tips', :as => :public_tips
  get 'belajar_investasi' => 'home#learning_module', :as => :public_module
  get 'berita/:slug' => 'home#news_view', :as => :public_news_view
  get 'tips_investasi/:slug' => 'home#investment_tips_view', :as => :public_tips_view
  get 'pencarian' => 'home#perform_search', :as => :public_perform_search
  get 'team' => 'home#team', :as => :public_team
  get 'terms' => 'home#terms', :as => :public_terms
  get 'about' => 'home#about_us', :as => :public_about_us
  get 'contact' => 'home#contact_us', :as => :public_contact_us
  get 'unsubscribe' => 'home#unsubscribe', :as => :public_unsubscribe
  get 'check_email' => 'home#check_email', :as => :public_check_email
  post 'contact' => 'home#send_contact', :as => :public_send_contact

  devise_for :admins

  namespace :admins do
    get 'dashboard' => 'dashboard#index'
    get 'preferences' => 'dashboard#preferences'

    post 'preferences' => 'dashboard#save_preferences'

    put 'update_full_name' => 'dashboard#update_full_name'
    put 'update_password' => 'dashboard#update_password'

    resources :admins, :except => [:show, :edit]
    resources :tags, :except => [:show]
    resources :glosarries
    resources :news
    resources :newsletter_queues
    resources :learning_modules
    resources :investment_tips
    resources :contacts, :only => [:index, :show, :destroy] do
      post 'set_subscribe_flag'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_preference
  before_action :set_latest_news, :except => [:index, :learning_module, :perform_search]
  before_action :set_banner_ad, :only => [:index, :learning_module]
  before_action :set_rectangle_ad, :except => [:index, :learning_module]

  def index
    @hot_news = @preference.news || News.last|| News.new
    @news = News.order(:created_at => :desc).limit(4)
    @tips = InvestmentTip.order(:created_at => :desc).limit(3)
    @glossaries = Glosarry.order(:created_at => :desc).limit(3)
  end

  def my_news
    @news = News.includes(:tags).by_tag(params[:tag])
                .search(params[:query]).order(:created_at => :desc)
                # .page(params[:page]).per(10)
  end

  def glossary
    @word_indexes = [*('A'..'Z')]
    @glossaries = Glosarry.search(params[:query]).order(:title => :asc)
  end

  def investment_tips
    @tips = InvestmentTip.search(params[:query]).order(:created_at => :desc)
                         # .page(params[:page]).per(10)
  end

  def learning_module
  end

  def news_view
    @news = News.includes(:tags).find_by_slug(params[:slug])
    raise ActiveRecord::RecordNotFound unless @news
    @related = News.find_related(@news).limit(3)
  end

  def investment_tips_view
    @tip = InvestmentTip.find_by_slug(params[:slug])
    raise ActiveRecord::RecordNotFound unless @tip
  end

  def perform_search
    @news = News.search(params[:query]).order(:created_at => :desc)
    @news_count = @news.count
    @news = @news.limit(5)

    @tips = InvestmentTip.search(params[:query]).order(:created_at => :desc)
    @tips_count = @tips.count
    @tips = @tips.limit(5)

    @glossaries = Glosarry.search(params[:query]).order(:title => :asc)
    @glossaries_count = @glossaries.count
    @glossaries = @glossaries.limit(5)

    @total_count = @news_count + @tips_count + @glossaries_count
  end

  def contact_us
  end

  def unsubscribe
    contact = Contact.find(params[:id])
    contact_token = Digest::MD5.hexdigest(contact.created_at.to_i.to_s)
    token = params[:token]
    raise ActiveRecord::RecordNotFound unless contact_token.eql?(token)
    contact.update(:is_subscribed => false)
    redirect_to root_url
  end

  def send_contact
    # if verify_recaptcha
    full_name = params[:name]
    email = params[:email]
    message = params[:message].class.eql?(Array) ? params[:message].first : params[:message]
    subscribe = params[:subscribe].to_i
    contact = Contact.find_or_initialize_by(:email => email)

    if contact.new_record?
      contact.name = full_name
      contact.message = message
      contact.is_subscribed = subscribe.eql?(1)
      contact.save
    end
    ApplicationMailer.contact_us(params).deliver_now
    # end

    redirect_to :back
  end

  def check_email
    contact = Contact.find_by(email: params[:email]) rescue nil
    msg = (contact.present?) ? "Email yang anda cantumkan sudah terdaftar" : nil
    respond_to do |format|
      format.json {render json: {status: 200,msg: msg}}
    end
  end

  def team
  end

  def terms
  end

  def about_us
  end

  private

    def set_latest_news
      @latest_news = News.order(:created_at => :desc).limit(4)
    end

    def set_preference
      @preference = Preference.fetch || Preference.new
    end

    def set_banner_ad
      @ad_code = @preference.banner_ad_script
    end

    def set_rectangle_ad
      @ad_code = @preference.sidebar_ad_script
    end
end

app/helpers/home_helper.rb
module HomeHelper
  def navbar_class_for_action
    controller.action_name.eql?('index') ? '' : 'scrolled'
  end

  def full_image_url_for(url)
    return nil if url.blank?
    URI::join(root_url, url).to_s
  end

  def generate_keywords_from(content)
    result = ['investasiku', 'investasi', 'belajar']
    counter = WordsCounted.count(content).token_frequency
    counter.each do |word|
      break if result.count.eql?(20)
      result << word[0]
    end
    result
  end
end

app/views/home/about_us.html.erb
<%
  set_meta_tags og: {
    :url => request.original_url,
    :title => 'Investasiku',
    :description => 'Mapan finansial bisa dimulai sekarang',
    :image => asset_url('home-top.png')
  }
%>

<div class="glossary-page">
  <div class="container-fluid">
    <div class="row">
      <div class="container">
        <div class="row">
          <div class="col-xs-12 investment-left">
            <div class="glossary-header tim clearfix">
              <div class="col-md-12 no-padding">
                <h3 class="investasiku-color uppercase">Tentang Kami</h3>
                <p class="">
                  Kami percaya bahwa sistem keuangan inklusif merupakan salah satu kunci utama dalam membangun kualitas kehidupan masyarakat di Indonesia. Selain untuk mendorong pertumbuhan ekonomi negara, partisipasi sektor keuangan yang inklusif dapat menguntungkan perkembangan masyarakat dalam menanggulangi kesenjangan antarindividu. Investasiku merupakan sebuah platform online yang dirancang untuk mengedukasi pembaca mengenai keuntungan dan cara-cara investasi, dengan fokus khusus di investasi reksadana.<br><br>
                  <h4>Kenapa reksadana?</h4>
                  Kami percaya bahwa reksadana merupakan salah satu bentuk investasi yang mudah, sekaligus dapat mempromosikan kesadaran keuangan. Mengapa?<br><br>
                  <h5>1. Ketersediaan</h5>
                  Dengan adanya unit reksadana di banyak bank di seluruh nusantara, sangat mudah untuk memilih reksadana sebagai bentuk investasi, dimana pun kamu berada<br><br>
                  <h5>2. Terjangkau</h5>
                  Harga tiap unit reksadana sangat terjangkau, sehingga dapat dibeli oleh masyarakat dari berbagai kalangan, dalam jumlah berapapun<br><br>
                  <h5>3. Terdiversifikasi</h5>
                  Dibandingkan berinvestasi dalam satu tempat, reksadana memungkinkan kamu untuk menaruh investasi di berbagai macam instrumen, hanya dengan melewati satu pintu Ingin tahu lebih lanjut mengenai reksadana? <%= link_to 'Klik di sini!', public_module_path %><br><br>
                  <h4>Tujuan</h4>
                  Investasiku beroperasi berdasarkan dua prinsip utama:<br><br>
                  <h5>1. Komprehensif</h5>
                  Memberikan informasi yang lengkap, akurat, dan relevan untuk mendukung keputusan investasi para pembaca<br><br>
                  <h5>2. Mudah dimengerti</h5>
                  Dalam membangun proses pembelajaran pembaca, kami bertujuan untuk menyajikan informasi yang mudah dimengerti dalam format yang tidak membosankan Apakah kamu mempunyai pertanyaan mengenai situs ini? Hubungi kami!
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/contact_us.html.erb
<%
  set_meta_tags og: {
    :url => request.original_url,
    :title => 'Investasiku',
    :description => 'Mapan finansial bisa dimulai sekarang',
    :image => asset_url('home-top.png')
  }
%>

<div class="container contact-us">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h2 class="comp-name">Kontak Kami</h2>
      <p><i class="fa fa-envelope-o" aria-hidden="true"></i>&nbsp;<%= mail_to 'admin@investasi-ku.com' %></p>
      <hr>
      <%= form_tag public_send_contact_path, :class => 'contact-us' do %>
        <div class="form-group">
          <%= text_field_tag :name, '', :placeholder => 'Nama', :class => 'form-control', :required => true %>
        </div>
        <div class="form-group">
          <%= email_field_tag :email, '', :placeholder => 'Email', :class => 'form-control', :required => true %>
        </div>
        <div class="form-group">
          <%= text_area_tag :message, '', :placeholder => 'Pertanyaan kamu', :rows => 9, :id => 'messages', :class => 'form-control', :required => true %>
        </div>
        <div class="form-group">
          <%= recaptcha_tags %>
        </div>
        <button type="submit" class="btn btn-primary contact">Send Message</button>
      <% end %>
    </div>
  </div>
</div>

app/views/home/glossary.html.erb
<%
  set_meta_tags title: 'Investasiku', site: 'Glosarium'
  set_meta_tags description: 'Belajar investasi itu mudah loh!'
  set_meta_tags keywords: %w[investasiku investasi belajar glossary glossaries kamus kata glosarium]
  set_meta_tags og: {
    :url => request.original_url,
    :title => 'Investasiku',
    :description => 'Mapan finansial bisa dimulai sekarang',
    :image => asset_url('home-top.png')
  }
%>

<div class="glossary-page">
  <div class="container-fluid">
    <div class="row">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-xs-12 glossary-left">
            <div class="glossary-header clearfix border-bottom">
              <div class="col-md-6 no-padding">
                <h3 class="investasiku-color uppercase">Glosarium</h3>
              </div>

              <%= render :partial => 'home/shared/form_search_context', :locals => { :route => public_glossary_path, :placeholder => 'Cari Glosarium...' } %>
            </div>
            <div id="glossary-list">
              <%= render 'home/ajax/glossary_list_item' %>
            </div>
          </div>

          <%= render 'home/shared/latest_news_side' %>

          <div class="pagination fixed-left scrollable">
            <% @word_indexes.each do |word| %>
              <%= link_to word, '#' + word, :class => 'investasiku-bg-color uppercase white glo-page active' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= content_for :javascript do %>
<script>
  window.should_enable_hash_inspector = true;
</script>
<% end %>

app/views/home/index.html.erb
<%
  set_meta_tags description: 'Belajar investasi itu mudah loh!'
  set_meta_tags keywords: %w[investasiku investasi belajar]
  set_meta_tags og: {
    :url => request.original_url,
    :title => 'Investasiku',
    :description => 'Mapan finansial bisa dimulai sekarang',
    :image => asset_url('home-top.png')
  }
%>

<div class="front-page top-section">
  <div class="container-fluid">
    <div class="row">
      <div class="home-jumbotron">
        <div class="col-xs-12 front-body-headline">
          <div class="text-center">
            <h2 class="white">Selamat datang di Investasiku,</h2>
            <p class="white">Mapan finansial bisa dimulai dari sekarang. Pahami investasi dan cara memonitornya di sini</p>
            <%= link_to 'Mulai dari sini!', public_module_path, :class => 'white invest-btn text-center' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="jumbotron-split">
        <!--<div class="col-md-6 col-sm-12 col-xs-12 front-pad-right border-right" style="background: url(<%= image_url('home-beritaku.jpg') %>); background-size:cover; background-position:center">
          <div class="headline-split vertical-middle">
            <div class="section-badge tema beritaku-sect">Beritaku</div>
            <div class="pull-left split-width">
              <h4 class="white">Berita terpenting untuk investasimu!</h4>
              <%= link_to 'Lebih Lanjut', public_news_path, :class => 'invest-color' %>
            </div>
          </div>
        </div>-->

        <!--<div class="col-md-6 col-sm-12 col-xs-12 front-pad-right">
          <div class="headline-split vertical-middle">
            <div class="section-badge tema beritaku-sect">Tips Investasi</div>
            <div class="pull-left split-width">
              <h4 class="white">Dapatkan tips untuk mengatur investasimu</h4>
              <%= link_to 'Lebih Lanjut', public_tips_path, :class => 'invest-color' %>
            </div>
          </div>
        </div>-->

        <% image_url = @preference.news.image_url rescue image_url('home-beritaku.jpg') %>
        <div class="col-md-6 col-sm-12 col-xs-12 front-pad-right border-right" style="background: url(<%= image_url %>); background-size:cover; background-position:center">
          <div class="headline-split vertical-middle">
            <div class="section-badge tema beritaku-sect">Beritaku</div>
            <div class="pull-left split-width">
              <h4 class="white"><%= truncate(@preference.news.title, :length => 64) rescue 'Berita terpenting untuk investasimu!' %></h4>
              <% path = public_news_view_path(@preference.news.slug) rescue public_news_path %>
              <%= link_to 'Lebih Lanjut', path, :class => 'invest-color' %>
            </div>
          </div>
        </div>

        <div class="col-md-6 col-sm-12 col-xs-12 front-pad-right">
          <div class="headline-split vertical-middle">
            <div class="section-badge tema beritaku-sect">Tips Investasi</div>
            <div class="pull-left split-width">
              <h4 class="white"><%= truncate(@preference.investment_tip.title, :length => 64) rescue 'Dapatkan tips untuk mengatur investasimu' %></h4>
              <% path = public_tips_view_path(@preference.investment_tip.slug) rescue public_tips_path %>
              <%= link_to 'Lebih Lanjut', path, :class => 'invest-color' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'home/shared/ad_view' %>

<div class="front-page bottom-section">
  <div class="container">
    <div class="row">
      <h2 class="investasiku-color text-center">Investasi tidak sulit kok !</h2>
      <p class="text-center">kami di sini untuk membantu kamu belajar berinvestasi, memahami isi berita dan jargon finansial, dan memberikan tips investasi berkala. </p>
      <div class="front-beritaku col-md-4 col-xs-12">
        <div class="row">
          <%= link_to public_news_path do %>
            <div class="hot top-beritaku" style="background: url(<%= image_url('home-beritaku.jpg') %>); background-size:cover; background-position:center">
              <div class="section-badge tema beritaku-sect">Beritaku</div>
              <div class="pull-left split-width">
                <h4 class="white">Berita terpenting untuk investasimu!</h4>
              </div>
            </div>
          <% end %>

          <% @news.each do |news| %>
            <div class="front-beritaku-small border-bottom">
              <%= link_to public_news_view_path(news.slug), :class => 'sect-child row no-margin' do %>
                <div class="beritaku-wrapper">
                  <%= image_tag news.image_url || 'tax.jpg', :class => 'imej' %>
                </div>
                <div class="headline-small-sect">
                  <h5 class="investasiku-color"><%= news.title %></h5>
                  <p class="font-12 grey"><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;<%= l news.created_at %></p>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="front-investment-theme col-md-4 col-xs-12">
        <div class="row">
          <%= link_to public_tips_path do %>
            <div class="hot top-investment" style="background: url(<%= image_url('home-investment.jpg') %>); background-size:cover; background-position:center">
              <div class="section-badge tema beritaku-sect">Tips Investasi</div>
              <div class="pull-left split-width">
                <h4 class="white">Dapatkan tips untuk mengurus investasimu</h4>
              </div>
            </div>
          <% end %>

          <% @tips.each do |tip| %>
            <div class="front-investment-small border-bottom">
              <%= link_to public_tips_view_path(tip.slug), :class => 'sect-child row no-margin' do %>
                <div class="headline-small-sect">
                  <h5 class="investasiku-color"><%= tip.title %></h5>
                  <p class="font-12 normal-font truncate-6"><%= strip_tags(tip.content) %></p>
                  <p class="font-12 grey"><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;<%= l tip.created_at %></p>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="front-glossary col-md-4 col-xs-12">
        <div class="row">
         <%= link_to public_glossary_path do %>
            <div class="hot top-investment" style="background: url(<%= image_url('home-glossary.jpg') %>); background-size:cover; background-position:center">
              <div class="section-badge tema beritaku-sect">Glosarium</div>
              <div class="pull-left split-width">
                <h4 class="white">Istilah-istilah yang perlu kamu kenal</h4>
              </div>
            </div>
          <% end %>

          <% @glossaries.each do |glossary| %>
            <div class="front-glossary-small border-bottom">
              <%= link_to public_glossary_path + '#' + glossary.title.parameterize, :class => 'sect-child row no-margin' do %>
                <div class="headline-small-sect">
                  <h5 class="investasiku-color"><%= glossary.title %></h5>
                  <p class="font-12 normal-font truncate-6"><%= glossary.description %></p>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= content_for :javascript do %>
<script>
  window.should_disable_scroll_inspector = false;
</script>
<% end %>

app/views/home/investment_tips.html.erb
<%
  set_meta_tags title: 'Investasiku', site: 'Tips Investasi'
  set_meta_tags description: 'Belajar investasi itu mudah loh!'
  set_meta_tags keywords: %w[investasiku investasi belajar tips investment tip]
    set_meta_tags og: {
    :url => request.original_url,
    :title => 'Investasiku',
    :description => 'Mapan finansial bisa dimulai sekarang',
    :image => asset_url('home-top.png')
  }
%>

<div class="glossary-page">
  <div class="container-fluid">
    <div class="row">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-xs-12 investment-left">
            <div class="glossary-header clearfix border-bottom">
              <div class="col-md-6 no-padding">
                <h3 class="investasiku-color uppercase">Tips Investasi</h3>
              </div>

              <%= render :partial => 'home/shared/form_search_context', :locals => { :route => public_tips_path, :placeholder => 'Cari Tips Investasi...' } %>
            </div>

            <div id="tips-list">
              <%= render 'home/ajax/tips_list_item' %>
            </div>
          </div>

          <%= render 'home/shared/latest_news_side' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/investment_tips.js.erb
$("#tips-list").html("<%= j render('home/ajax/tips_list_item') %>");
enableFormSearchContext();

app/views/home/investment_tips_view.html.erb
<%
  striped_tags = strip_tags(@tip.content)
  set_meta_tags title: 'Investasiku', site: @tip.title
  set_meta_tags description: truncate(striped_tags, :length => 160)
  set_meta_tags keywords: generate_keywords_from(striped_tags)
  set_meta_tags og: {
    :url => request.original_url,
    :title => @tip.title + ' | Investasiku',
    :description => truncate(striped_tags, :length => 160),
    :image => asset_url('home-top.png')
  }
%>

<div class="news-details invesment-view">
  <div class="container-fluid">
    <div class="row">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-xs-12 news-content investment-content">
            <ol class="breadcrumb transparent no-padding">
              <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
              <li class="breadcrumb-item active">Tips Investasi</li>
            </ol>
            <h3 class="investasiku-color"><%= @tip.title %></h3>
            <div class="time-publish"><p class="grey"><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;<%= l @tip.created_at %>&nbsp;</p></div>

            <%= raw @tip.content %>

            <p class="grey font-12">Posted by <b class="investasiku-color"><%= @tip.custom_posted_by || @tip.posted_by.full_name %></b></p>

            <%= render :partial => 'home/shared/share_buttons', :locals => { :minimal => false,
                                                                             :title => @tip.title,
                                                                             :url => public_tips_view_url(@tip.slug),
                                                                             :image => image_url('logo_color.png') } %>
          </div>

          <%= render 'home/shared/latest_news_side' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/my_news.html.erb
<%
  set_meta_tags title: 'Investasiku', site: 'Beritaku'
  set_meta_tags description: 'Belajar investasi itu mudah loh!'
  set_meta_tags keywords: %w[investasiku investasi belajar berita beritaku berita news]
  set_meta_tags og: {
    :url => request.original_url,
    :title => 'Investasiku',
    :description => 'Mapan finansial bisa dimulai sekarang',
    :image => asset_url('home-top.png')
  }
%>

<div class="beritaku-page">
  <div class="container-fluid">
    <div class="row">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-12 col-xs-12 beritaku">
            <div class="glossary-header clearfix border-bottom">
              <div class="col-sm-6 col-xs-12 no-padding">
                <h3 class="investasiku-color uppercase">Beritaku</h3>
              </div>

              <%= render :partial => 'home/shared/form_search_context', :locals => { :route => public_news_path, :placeholder => 'Cari Beritaku...' } %>
            </div>

            <div class="container-custom">
              <div id="news-list" class="row">
                <%= render 'home/ajax/news_list_item' %>
              </div>
            </div>
          </div>

          <%= render 'home/shared/latest_news_side' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/my_news.js.erb
$("#news-list").html("<%= j render('home/ajax/news_list_item') %>");
enableFormSearchContext();

app/views/home/news_view.html.erb
<%
  striped_tags = strip_tags(@news.content)
  set_meta_tags title: 'Investasiku', site: @news.title
  set_meta_tags description: truncate(striped_tags, :length => 160)
  set_meta_tags keywords: generate_keywords_from(striped_tags)
  set_meta_tags og: {
    :url => request.original_url,
    :title => @news.title + ' | Investasiku',
    :description => truncate(striped_tags, :length => 160),
    :image => @news.image_url
  }
%>

<div class="news-details">
  <div class="container-fluid">
    <div class="row">
      <div class="news-cover" style="background: url(<%= @news.image_url || image_url('tax.jpg') %>);">
      </div>

      <div class="container">
        <div class="row">
          <div class="col-md-8 col-xs-12 news-content">
            <ol class="breadcrumb transparent no-padding">
              <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
              <li class="breadcrumb-item active">Beritaku</li>
            </ol>
            <h3 class="investasiku-color"><%= @news.title %></h3>
            <div class="time-publish"><p class="grey"><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;<%= l @news.created_at %>&nbsp;</p></div>
            <div class="tag-group">
              <% @news.tags.each do |tag| %>
                <%= link_to tag.name, public_news_path + '?tag=' + tag.name, :class => 'news-type investasiku-bg' %>
              <% end %>
            </div>

            <%= raw @news.content %>

            <p class="grey font-12">Posted by <b class="investasiku-color"><%= @news.custom_posted_by || @news.posted_by.full_name %></b></p>

            <%= render :partial => 'home/shared/share_buttons', :locals => { :minimal => false,
                                                                             :title => @news.title,
                                                                             :url => public_news_view_url(@news.slug),
                                                                             :image => @news.image_url } %>
          </div>

          <%= render 'home/shared/latest_news_side' %>
        </div>
      </div>

      <% unless @related.blank? %>
        <div class="container-fluid related-news hidden-xs">
          <h4 class="related-header">Related news</h4>
          <div class="row">
            <div class="col-md-12 col-sm-12 border-top x-hidden">
              <div class="inner-container">
                <% @related.each do |news| %>
                  <div class="related front-beritaku-small border-right col-md-4 col-sm-4 col-xs-12">
                    <%= link_to public_news_path(news.slug), :class => 'sect-child row no-margin' do %>
                      <div class="beritaku-wrapper">
                        <%= image_tag news.image_url || 'tax.jpg', :class => 'imej' %>
                      </div>
                      <div class="headline-small-sect">
                        <h5 class="investasiku-color truncate-3"><%= news.title %></h5>
                        <p class="font-12 grey"><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;<%= l news.created_at %></p>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/perform_search.html.erb
<%
  set_meta_tags og: {
    :url => request.original_url,
    :title => 'Investasiku',
    :description => 'Mapan finansial bisa dimulai sekarang',
    :image => asset_url('home-top.png')
  }
%>

<div class="front-page bottom-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 title-pencarian">
        <h5 >Hasil pencarian "<%= params[:query] %>"</h5>
        <p class="grey">menemukan <%= @total_count %> hasil</p>
      </div>

      <div class="front-beritaku search col-md-4 col-xs-12">
        <div class="row">
          <%= link_to public_news_path({ :query => params[:query] }) do %>
            <h4 class="margin-bot-25 investasiku-color uppercase search-gen">Beritaku (<%= @news_count %>)</h4>
          <% end %>

          <% @news.each do |news| %>
            <div class="front-beritaku-small border-bottom">
              <%= link_to public_news_view_path(news.slug), :class => 'sect-child row no-margin' do %>
                <div class="beritaku-wrapper">
                  <%= image_tag news.image_url || image_url('tax.jpg'), :class => 'imej' %>
                </div>
                <div class="headline-small-sect">
                  <h5 class="investasiku-color"><%= news.title %></h5>
                  <p class="font-12 grey"><i class="fa fa-clock-o"></i>&nbsp;<%= l news.created_at %></p>
                </div>
              <% end %>
            </div>
            <% end %>
        </div>
      </div>

      <div class="front-investment-theme search col-md-4 col-xs-12">
        <div class="row">
          <%= link_to public_tips_path({ :query => params[:query] }) do %>
            <h4 class="margin-bot-25 investasiku-color uppercase search-general-tit">Tips Investasi (<%= @tips_count %>)</h4>
          <% end %>

          <% @tips.each do |tip| %>
            <div class="front-investment-small border-bottom">
              <%= link_to public_tips_view_path(tip.slug), :class => 'sect-child row no-margin' do %>
                <div class="headline-small-sect">
                  <h5 class="investasiku-color"><%= tip.title %></h5>
                  <p class="font-12 normal-font truncate-6"><%= strip_tags(tip.content) %></p>
                  <p class="font-12 grey"><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;<%= l tip.created_at %></p>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="front-glossary search col-md-4 col-xs-12">
        <div class="row">
          <%= link_to public_glossary_path({ :query => params[:query] }) do %>
            <h4 class="margin-bot-25 investasiku-color uppercase search-general-tit">Glosarium (<%= @glossaries_count %>)</h4>
          <% end %>

          <% @glossaries.each do |glossary| %>
            <div class="front-glossary-small border-bottom">
              <%= link_to public_glossary_path + '#' + glossary.title.parameterize, :class => 'sect-child row no-margin' do %>
                <div class="headline-small-sect">
                  <h5 class="investasiku-color"><%= glossary.title %></h5>
                  <p class="font-12 normal-font truncate-6"><%= glossary.description %></p>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>