config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'

  get 'berita' => 'home#my_news', :as => :public_news
  get 'glosarium' => 'home#glossary', :as => :public_glossary
  get 'tips_investasi' => 'home#investment_tips', :as => :public_tips
  get 'belajar_investasi' => 'home#learning_module', :as => :public_module
  get 'berita/:slug' => 'home#news_view', :as => :public_news_view
  get 'tips_investasi/:slug' => 'home#investment_tips_view', :as => :public_tips_view
  get 'pencarian' => 'home#perform_search', :as => :public_perform_search
  get 'team' => 'home#team', :as => :public_team
  get 'terms' => 'home#terms', :as => :public_terms
  get 'about' => 'home#about_us', :as => :public_about_us
  get 'contact' => 'home#contact_us', :as => :public_contact_us
  get 'unsubscribe' => 'home#unsubscribe', :as => :public_unsubscribe
  get 'check_email' => 'home#check_email', :as => :public_check_email
  post 'contact' => 'home#send_contact', :as => :public_send_contact

  devise_for :admins

  namespace :admins do
    get 'dashboard' => 'dashboard#index'
    get 'preferences' => 'dashboard#preferences'

    post 'preferences' => 'dashboard#save_preferences'

    put 'update_full_name' => 'dashboard#update_full_name'
    put 'update_password' => 'dashboard#update_password'

    resources :admins, :except => [:show, :edit]
    resources :tags, :except => [:show]
    resources :glosarries
    resources :news
    resources :newsletter_queues
    resources :learning_modules
    resources :investment_tips
    resources :contacts, :only => [:index, :show, :destroy] do
      post 'set_subscribe_flag'
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/admins/tags_controller.rb
class Admins::TagsController < Admins::BaseController
  before_action :set_tag, only: [:edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to admins_tags_path, notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to admins_tags_path, notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to admins_tags_path, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admins/tags/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for([:admins, tag], :html => { :class => 'form-horizontal' }) do |f| %>
          <% if tag.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <strong>Ops! <%= pluralize(tag.errors.count, "error") %> found:</strong><br/>
              <ul>
                <% tag.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :name, :class => 'col-sm-2 control-label' %>
            <div class="col-sm-10">
              <%= f.text_field :name, :class => 'form-control' %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 text-right">
              <%= link_to admins_tags_path, :class => 'btn btn-warning' do %>
                <span class="glyphicon glyphicon-menu-left"></span>&nbsp;Back
              <% end %>
            </div>
            <div class="col-md-6 text-left">
              <%= f.submit 'Save', :class => 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/tags/edit.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Tags', admins_tags_path %>
    <%= breadcrumb_item 'Edit Tag' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Edit <%= @tag.name.titleize %></h1>
  </div>
</div>

<%= render 'form', tag: @tag %>

app/views/admins/tags/index.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Tags' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">News Tag Management</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-striped table-hover">
          <%= link_to new_admins_tag_path, :class => 'btn btn-success pull-right' do %>
            <span class="glyphicon glyphicon-plus"></span>&nbsp;New Tag
          <% end %>
          <thead>
            <th>Name</th>
            <th>Control</th>
          </thead>

          <tbody>
            <tbody>
              <% if @tags.empty? %>
                <tr>
                  <td colspan="2">You have no tags. <%= link_to 'Create a new one!', new_admins_tag_path %>.</td>
                </tr>
              <% else %>
                <% @tags.each do |tag| %>
                  <tr>
                    <td><%= tag.name %></td>
                    <td>
                      <%= link_to 'Edit', edit_admins_tag_path(tag) %>&nbsp;|
                      <%= link_to 'Destroy', admins_tag_path(tag), :method => :delete, :data => { :confirm => 'Are you sure?' } %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admins/tags/new.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Tags', admins_tags_path %>
    <%= breadcrumb_item 'New Tag' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Create New Tag</h1>
  </div>
</div>

<%= render 'form', tag: @tag %>