config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'

  get 'berita' => 'home#my_news', :as => :public_news
  get 'glosarium' => 'home#glossary', :as => :public_glossary
  get 'tips_investasi' => 'home#investment_tips', :as => :public_tips
  get 'belajar_investasi' => 'home#learning_module', :as => :public_module
  get 'berita/:slug' => 'home#news_view', :as => :public_news_view
  get 'tips_investasi/:slug' => 'home#investment_tips_view', :as => :public_tips_view
  get 'pencarian' => 'home#perform_search', :as => :public_perform_search
  get 'team' => 'home#team', :as => :public_team
  get 'terms' => 'home#terms', :as => :public_terms
  get 'about' => 'home#about_us', :as => :public_about_us
  get 'contact' => 'home#contact_us', :as => :public_contact_us
  get 'unsubscribe' => 'home#unsubscribe', :as => :public_unsubscribe
  get 'check_email' => 'home#check_email', :as => :public_check_email
  post 'contact' => 'home#send_contact', :as => :public_send_contact

  devise_for :admins

  namespace :admins do
    get 'dashboard' => 'dashboard#index'
    get 'preferences' => 'dashboard#preferences'

    post 'preferences' => 'dashboard#save_preferences'

    put 'update_full_name' => 'dashboard#update_full_name'
    put 'update_password' => 'dashboard#update_password'

    resources :admins, :except => [:show, :edit]
    resources :tags, :except => [:show]
    resources :glosarries
    resources :news
    resources :newsletter_queues
    resources :learning_modules
    resources :investment_tips
    resources :contacts, :only => [:index, :show, :destroy] do
      post 'set_subscribe_flag'
    end
  end
end

app/views/admins/admins/index.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Admin Accounts' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Admin Management</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-striped table-hover">
          <%= link_to new_admins_admin_path, :class => 'btn btn-success pull-right' do %>
            <span class="glyphicon glyphicon-plus"></span>&nbsp;New Admin
          <% end %>
          <thead>
            <th>Full Name</th>
            <th>Email</th>
            <th>Last Login</th>
            <th>Last Login IP</th>
            <th>Control</th>
          </thead>

          <tbody>
            <tbody>
              <% @admins.each do |admin| %>
                <tr class="<%= 'info' if current_admin == admin %>">
                  <td><%= admin.full_name %></td>
                  <td><%= admin.email %></td>
                  <td><%= admin.last_sign_in_at %></td>
                  <td><%= admin.last_sign_in_ip %></td>
                  <td>
                    <% if current_admin != admin %>
                      <%= link_to 'Delete', admins_admin_path(admin), :method => :delete, :data => { :confirm => 'Are you sure?' } %>
                    <% else %>
                      N/A
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admins/admins/new.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Admin Accounts', admins_admins_path %>
    <%= breadcrumb_item 'New Admin' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Create New Admin</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for([:admins, @admin], :html => { :class => 'form-horizontal' }) do |f| %>
          <% if @admin.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <strong>Ops! <%= pluralize(@admin.errors.count, "error") %> found:</strong><br/>
              <ul>
                <% @admin.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :full_name, :class => 'col-sm-2 control-label' %>
            <div class="col-sm-10">
              <%= f.text_field :full_name, :class => 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :email, :class => 'col-sm-2 control-label' %>
            <div class="col-sm-10">
              <%= f.text_field :email, :class => 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :password, :class => 'col-sm-2 control-label' %>
            <div class="col-sm-10">
              <%= f.password_field :password, :class => 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'Retype password', :class => 'col-sm-2 control-label' %>
            <div class="col-sm-10">
              <%= f.password_field :password_confirmation, :class => 'form-control' %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 text-right">
              <%= link_to admins_admins_path, :class => 'btn btn-warning' do %>
                <span class="glyphicon glyphicon-menu-left"></span>&nbsp;Back
              <% end %>
            </div>
            <div class="col-md-6 text-left">
              <%= f.submit 'Save', :class => 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>