config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'

  get 'berita' => 'home#my_news', :as => :public_news
  get 'glosarium' => 'home#glossary', :as => :public_glossary
  get 'tips_investasi' => 'home#investment_tips', :as => :public_tips
  get 'belajar_investasi' => 'home#learning_module', :as => :public_module
  get 'berita/:slug' => 'home#news_view', :as => :public_news_view
  get 'tips_investasi/:slug' => 'home#investment_tips_view', :as => :public_tips_view
  get 'pencarian' => 'home#perform_search', :as => :public_perform_search
  get 'team' => 'home#team', :as => :public_team
  get 'terms' => 'home#terms', :as => :public_terms
  get 'about' => 'home#about_us', :as => :public_about_us
  get 'contact' => 'home#contact_us', :as => :public_contact_us
  get 'unsubscribe' => 'home#unsubscribe', :as => :public_unsubscribe
  get 'check_email' => 'home#check_email', :as => :public_check_email
  post 'contact' => 'home#send_contact', :as => :public_send_contact

  devise_for :admins

  namespace :admins do
    get 'dashboard' => 'dashboard#index'
    get 'preferences' => 'dashboard#preferences'

    post 'preferences' => 'dashboard#save_preferences'

    put 'update_full_name' => 'dashboard#update_full_name'
    put 'update_password' => 'dashboard#update_password'

    resources :admins, :except => [:show, :edit]
    resources :tags, :except => [:show]
    resources :glosarries
    resources :news
    resources :newsletter_queues
    resources :learning_modules
    resources :investment_tips
    resources :contacts, :only => [:index, :show, :destroy] do
      post 'set_subscribe_flag'
    end
  end
end

app/models/newsletter_queue.rb
class NewsletterQueue < ApplicationRecord
  validates_presence_of :subject, :content

  enum :status => [:queued, :processing, :sent, :failed]

  # used by rake cron task to broadcast newsletters
  def broadcast(contact)
    self.processing!
    ApplicationMailer.newsletters(contact, self).deliver_now rescue self.failed!
    self.sent!
  end
end

app/controllers/admins/newsletter_queues_controller.rb
class Admins::NewsletterQueuesController < Admins::BaseController
  before_action :set_newsletter_queue, only: [:show, :edit, :update, :destroy]

  # GET /newsletter_queues
  def index
    @newsletter_queues = NewsletterQueue.all
  end

  # GET /newsletter_queues/1
  def show
  end

  # GET /newsletter_queues/new
  def new
    @newsletter_queue = NewsletterQueue.new
  end

  # GET /newsletter_queues/1/edit
  def edit
  end

  # POST /newsletter_queues
  def create
    @newsletter_queue = NewsletterQueue.new(newsletter_queue_params)

    if @newsletter_queue.save
      redirect_to admins_newsletter_queues_path, notice: 'Newsletter queue was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /newsletter_queues/1
  def update
    if @newsletter_queue.update(newsletter_queue_params)
      redirect_to admins_newsletter_queues_path, notice: 'Newsletter queue was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /newsletter_queues/1
  def destroy
    @newsletter_queue.destroy
    redirect_to admins_newsletter_queues_path, notice: 'Newsletter queue was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter_queue
      @newsletter_queue = NewsletterQueue.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def newsletter_queue_params
      params.require(:newsletter_queue).permit(:subject, :content)
    end
end

app/helpers/newsletter_queues_helper.rb
module NewsletterQueuesHelper
end

app/views/admins/newsletter_queues/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for([:admins, newsletter_queue], :html => { :class => 'form-horizontal' }) do |f| %>
          <% if newsletter_queue.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <strong>Ops! <%= pluralize(newsletter_queue.errors.count, "error") %> found:</strong><br/>
              <ul>
                <% newsletter_queue.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.label :subject, :class => 'col-sm-2 control-label' %>
            <div class="col-sm-10">
              <%= f.text_field :subject, :class => 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :content, :class => 'col-sm-2 control-label' %>
            <div class="col-sm-10">
              <%= f.cktext_area :content, :class => 'ckeditor' %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 text-right">
              <%= link_to admins_newsletter_queues_path, :class => 'btn btn-warning' do %>
                <span class="glyphicon glyphicon-menu-left"></span>&nbsp;Back
              <% end %>
            </div>
            <div class="col-md-6 text-left">
              <%= f.submit 'Save', :class => 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/newsletter_queues/edit.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Newsletter Queue', admins_newsletter_queues_path %>
    <%= breadcrumb_item 'Edit Queue' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Edit <%= @newsletter_queue.subject %></h1>
  </div>
</div>

<%= render 'form', newsletter_queue: @newsletter_queue %>

app/views/admins/newsletter_queues/index.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Newsletter Queues' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Newsletter Queues</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-striped table-hover">
          <%= link_to new_admins_newsletter_queue_path, :class => 'btn btn-success pull-right' do %>
            <span class="glyphicon glyphicon-plus"></span>&nbsp;Add Queue
          <% end %>
          <thead>
            <th>Subject</th>
            <th>Status</th>
            <th>Control</th>
          </thead>

          <tbody>
            <tbody>
              <% if @newsletter_queues.empty? %>
                <tr>
                  <td colspan="3">You have no queues. <%= link_to 'Add a new one!', new_admins_newsletter_queue_path %>.</td>
                </tr>
              <% else %>
                <% @newsletter_queues.each do |newsletter_queue| %>
                  <tr>
                    <td><%= newsletter_queue.subject %></td>
                    <td><%= newsletter_queue.status %></td>
                    <td>
                      <%= link_to 'Preview', admins_newsletter_queue_path(newsletter_queue) %>
                      <% if newsletter_queue.queued? %>
                        &nbsp;|
                        <%= link_to 'Edit', edit_admins_newsletter_queue_path(newsletter_queue) %>&nbsp;|
                        <%= link_to 'Destroy', admins_newsletter_queue_path(newsletter_queue), :method => :delete, :data => { :confirm => 'Are you sure?' } %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admins/newsletter_queues/new.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Newsletter Queue', admins_newsletter_queues_path %>
    <%= breadcrumb_item 'Add Queue' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Add Queue</h1>
  </div>
</div>

<%= render 'form', newsletter_queue: @newsletter_queue %>

app/views/admins/newsletter_queues/show.html.erb
<div class="row">
  <%= breadcrumb do %>
    <%= breadcrumb_item %>
    <%= breadcrumb_item 'Newsletter Queue', admins_newsletter_queues_path %>
    <%= breadcrumb_item 'Preview' %>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= @newsletter_queue.subject %></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <% case @newsletter_queue.status %>
          <% when 'queued' %>
            <div class="text-info"><span class="glyphicon glyphicon-hourglass"></span>&nbsp;Scheduled tonight</div>
          <% when 'processing' %>
            <div class="text-warning"><span class="glyphicon glyphicon-plane"></span>&nbsp;Broadcasting</div>
          <% when 'sent' %>
            <div class="text-success"><span class="glyphicon glyphicon-send"></span>&nbsp;Broadcasted</div>
          <% when 'failed' %>
            <div class="text-danger"><span class="glyphicon glyphicon-remove"></span>&nbsp;Failed</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= @newsletter_queue.content.html_safe %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to admins_newsletter_queues_path, :class => 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-menu-left"></span>&nbsp;Back
        <% end %>
        <% if @newsletter_queue.queued? %>
          <%= link_to edit_admins_newsletter_queue_path(@newsletter_queue), :class => 'btn btn-info' do %>
            <span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>